# Dependencies
markdown:         kramdown
highlighter:      pygments

# Permalinks
permalink:        pretty
gems: [jekyll-paginate]

# Setup
title:            R . Roboter
description:      'Put yourself in a position where you have no other option other than to make sure that project gets built.'
url:              http://rroboter.github.io
baseurl:          /
logo:             /content/images/logo.jpg

author:
  name:           'R . Roboter'
  url:            https://github.com/RRoboter

paginate:         5

disqus_shortname: rroboter

github:
  repo:           https://github.com/RRoboter/rroboter.github.io.git

kramdown:
  # Enable GitHub Flavored Markdown (fenced code blocks)
  input: GFM
  syntax_highlighter: rouge